### ISSUE TITLE
Most "slow-cycle" carbon credits don't meet #9 of ICVCM so how can any be accepted to Nori program?

### ISSUE THREAD

**Issue by Beto-carbon** [nori-dot-eco/carbon-removal-whitepapers#1]
The white paper states that "slow-cycle" credits must meet "some set of common standards" and lists the ICVCM core carbon principles

The problem is that the core carbon principles don't work for engineered carbon removal (E-CDR). Principle #9 states:

_The carbon-crediting program shall have clear guidance, tools and compliance procedures to ensure mitigation activities conform with or go beyond widely established industry best practices on social and environmental safeguards while delivering positive sustainable development impacts._  

The obvious intention of the last sentence is to say that the credit must have co-benefits.  The problem is that E-CDR, almost by definition, has no co-benefits.  One could invent the lowest cost DACC process that breaks the rules of thermodynamics but it just sucks carbon out of the sky, nothing else...

This ICVCM verbiage is already being used by the nature-only movement, who argue that E-CDR is morally wrong.  It's not clear if ICVCM the wording was intentional or merely the result of a statement written by a huge committee but never actually thought through holistically.

Like all written agreements, we can try and sneak around the ICVCM:

UN SDG #13: climate action - this is 100% self referential
UN SDG #8: decent work and economic growth - maybe your DACCS plant hires some people, preferable union or apprentices.

But, it would make more sense to confront the issue head-on and state that if a methodology is scientifically sound for carbon removal and does no social-environmental harm, then it is valid for helping save humankind from climate change.

**Comment by rickberg227** [comment]
Thank you for the input. While co-benefits beyond the climate benefits of carbon removal itself can be valuable, Nori is not planning on making them a required characteristic of removals that are sold in the marketplace. The standards listed in the whitepaper are given as examples of the common standards that are emerging in the CDR markets, they are not listed to imply Nori will require certification by those organizations as part of our approval process. We aim to ensure that all removals sold through our marketplace have real, sustainable impact. As part of that, social and environmental safeguards must be in place for CDR projects to be successful, including for both engineered and nature-based solutions.

**Comment by Beto-carbon** [comment]
Social and environmental safeguards absolutely - first "do no harm".  I do think organizations like Nori need to be clear that net-zero targets and long-cycle carbon removal shouldn't get dragged into other constituencies more nebulous development goals.  Reaching the targets needed for 2°C is going to hard enough without complicating matters with "SDG-washing".

I look forward to seeing how this endeavor develops.
